### ISSUE TITLE
Add mod_info.yaml to root directory of uploaded mods

### ISSUE THREAD

**Issue by nevarek** [Mayall0513/oni-mods#1]
Looks like the convention for ONI mods now requires a `mod_info.yaml` file to support marking mods for working with the DLC.

> Currently published mods will still function as intended, and the game will just assume they were designed for the base game. Going forward, the mod uploader will require mod_info.yaml, so all new mods need to declare which versions they support, and what build number of the game they were tested on.

https://forums.kleientertainment.com/forums/topic/126022-setting-up-mod_infoyaml/

If you need help implementing this, I offer this file content:
```
# supported values: VANILLA_ID, EXPANSION1_ID, ALL
supportedContent: ALL

# latest version this mod was "tested" on
lastWorkingBuild: 447598
```

That build version might have to be changed, since it's dependent on what you use. That's the version I have though.

**Comment by nevarek** [comment]
here's also an example from another modder https://github.com/Zonkeeh/ONI-Mods/blob/master/DestructibleFeatures/mod_info.yaml

**Comment by BolderDufta** [comment]
Thank you
